# version: 2
# updates:
#   - package-ecosystem: "maven"
#     directory: "/"
#     schedule:
#       interval: "weekly"
#     target-branch: "main"
#     reviewers:
#       - "vasanth-123"

#   - package-ecosystem: "maven"
#     directory: "/"
#     schedule:
#       interval: "weekly"
#     target-branch: "spring"
#     reviewers:
#       - "vasanth-123"
version: 2
updates:
  - package-ecosystem: "maven"
   directory: "/demo1/demo1"
    schedule:
      interval: "daily"
    target-branch: "main"
    reviewers:
      - "vasanth-123"
