updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    reviewers:
      - "vasanth-123"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "spring"
    reviewers:
      - "vasanth-123"